version: "2"

services:
  master:
    build: .
    container_name: master
    volumes:
      - /etc/redis/masterSlave/master.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.22.0.2
  slave1:
    build: .
    container_name: slave1
    volumes:
      - /etc/redis/masterSlave/slave1.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.22.0.3
  slave2:
    build: .
    container_name: slave2
    volumes:
      - /etc/redis/masterSlave/slave2.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.22.0.4
  slave3:
    build: .
    container_name: slave3
    volumes:
      - /etc/redis/masterSlave/slave3.conf:/usr/local/etc/redis/redis.conf
    networks:
      redisnet:
        ipv4_address: 172.22.0.5
networks:
  redisnet:
    ipam:
      config:
      - subnet: 172.22.0.0/16
        gateway: 172.22.0.1